---
# Author:       Brian Sigurdson sigurdson.brian@gmail.com
# Date:         2018-10-30
# Description:  
# If the specified version of WildFly already exists on a node, then the playbook will
# fail for that node.  The playbook will continue processing the remaining nodes, again, 
# failing if the specified version aleady exists on a node.
# 
# Therefore, the playbook will only do an initial installation, and can be run at anytime, 
# such as when adding a new node.

########################################################################################
# start playbook
########################################################################################

- name: Deploy WildFly {{ jboss_wildfly_verision }}
  hosts: slaves
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo 
  connection: ssh
  gather_facts: no

  vars_files:
    - ../local_variable_files/local-vars.yml


########################################################################################
# start tasks
########################################################################################

  tasks:
  - name: Gather facts about "{{ jboss_wildfly_install }}" and exit if it already exits.
    stat:
      path: "{{ jboss_wildfly_install }}"
    register: p

  - fail:
      msg: "{{ jboss_wildfly_install }} Already exists.  Run the delete script to remove jboss_wildfly {{ jboss_wildfly_version }}, then rerun the deploy scipt."
    when: p.stat.isdir is defined and p.stat.isdir

  - name: create {{ jboss_wildfly_base }}, if it does not exist
    file:
      path: "{{ jboss_wildfly_base }}"
      state: directory
      mode: 0755
      owner: "{{ jboss_wildfly_user_name }}"
      group: "{{ jboss_wildfly_user_group }}"
      recurse: yes

  - name: Copy and extract {{ jboss_wildfly_compressed_dir }}/{{ jboss_wildfly_file_name }} on source to {{ jboss_wildfly_base }} on remote
    unarchive:
      src: "{{ jboss_wildfly_compressed_dir }}/{{ jboss_wildfly_file_name }}"
      dest: "{{ jboss_wildfly_base }}"

  - name: mv {{ jboss_wildfly_base }}/wildfly-{{ jboss_wildfly_version }} to {{ jboss_wildfly_install }}
    command: mv {{ jboss_wildfly_base }}/wildfly-{{ jboss_wildfly_version }} {{ jboss_wildfly_install }}

  - name: Ensure {{ jboss_wildfly_user_name }} is owner of {{ jboss_wildfly_base }} and all contents
    file:
      path: "{{ jboss_wildfly_base }}"
      owner: "{{ jboss_wildfly_user_name }}"
      group: "{{ jboss_wildfly_user_group }}"
      recurse: yes 

# delete temp files that tend to accumulate in the user ansible's home dir
# place at the bottom of all playbooks
  - include: ../../local_includes/delete-ansible-tmp-files.yml
