---
# Author:       Brian Sigurdson sigurdson.brian@gmail.com
# Date:         2018-10-31
# Description:  Start WildFly

# The following page was very helpful in competing this task.
# https://community.i2b2.org/wiki/display/getstarted/2.4.2.3+Run+Wildfly+as+a+Linux+Service

########################################################################################
# start playbook
########################################################################################

- name: Start WildFly {{ jboss_wildfly_verision }} for {{ ansible_default_ipv4.address }}
  hosts: slaves
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo 
  connection: ssh
  gather_facts: true
  vars:
    wildfly_conf_sym_file:  /etc/default/wildfly.conf
    wildfly_init_sym_file:  /etc/init.d/wildfly
    java_home:  /usr/lib/jvm/java

  vars_files:
    - ../local_variable_files/local-vars.yml

########################################################################################
# start tasks
########################################################################################

  tasks:
  - file:
      src: "{{ jboss_wildfly_install }}/bin/init.d/wildfly.conf"
      dest: "{{ wildfly_conf_sym_file }}"
      owner: "{{ jboss_wildfly_user_name }}"
      group: "{{ jboss_wildfly_user_group }}"
      state: link

  - file:
      src: "{{ jboss_wildfly_install }}/bin/init.d/wildfly-init-redhat.sh"
      dest: "{{ wildfly_init_sym_file }}"
      owner: "{{ jboss_wildfly_user_name }}"
      group: "{{ jboss_wildfly_user_group }}"
      state: link

  - name: "echo JAVA_HOME={{ java_home }} >> {{ wildfly_conf_sym_file }}"
    shell: "echo JAVA_HOME={{ java_home }} >> {{ wildfly_conf_sym_file }}"

  - name: "echo JBOSS_HOME={{ jboss_wildfly_install }} >> {{ wildfly_conf_sym_file }}"
    shell: "echo JBOSS_HOME={{ jboss_wildfly_install }} >> {{ wildfly_conf_sym_file }}"

  - name: "echo JBOSS_USER={{ jboss_wildfly_user_name }} >> {{ wildfly_conf_sym_file }}"
    shell: "echo JBOSS_USER={{ jboss_wildfly_user_name }} >> {{ wildfly_conf_sym_file }}"

  - name: "echo JBOSS_MODE={{ jboss_wildfly_operating_mode }} >> {{ wildfly_conf_sym_file }}"
    shell: "echo JBOSS_MODE={{ jboss_wildfly_operating_mode }} >> {{ wildfly_conf_sym_file }}"

  # - name: "ln -s {{ jboss_wildfly_install }}/bin/init.d/wildfly-init-redhat.sh /etc/init.d/wildfly"
  #   shell: "ln -s {{ jboss_wildfly_install }}/bin/init.d/wildfly-init-redhat.sh /etc/init.d/wildfly"

  # - debug:
  #   msg: "System ip address {{ ansible_default_ipv4.address }}"

  # - debug: var=ansible_all_ipv4_addresses
  # - debug: var=ansible_default_ipv4.address

  # - set_fact: local_ip_addr="{{ ansible_default_ipv4.address }}"

  # - debug: 
  #     msg: "the variable ansible_default_ipv4.address = {{ ansible_default_ipv4.address }}"

  # - debug: 
  #     msg: "the variable var = {{ local_ip_addr }}"

  # - name: "{{ jboss_wildfly_install }}/bin/standalone.sh -Djboss.bind.address={{ ansible_default_ipv4.address }} &"
  #   shell: "{{ jboss_wildfly_install }}/bin/standalone.sh -Djboss.bind.address={{ ansible_default_ipv4.address }} &"
  #   become: yes
  #   become_user: "{{ jboss_wildfly_user_name }}"



# delete temp files that tend to accumulate in the user ansible's home dir
# place at the bottom of all playbooks
  - include: ../../local_includes/delete-ansible-tmp-files.yml
