---
# Author:       Brian Sigurdson sigurdson.brian@gmail.com
# Date:         2018-10-31
# Description:  Setup compressed file dir

# The following page was very helpful in competing this task.
# https://docs.jboss.org/author/display/WFLY/Command+Line+Interface

########################################################################################
# start playbook
########################################################################################

- name: Deploy app1_v01.war
  hosts: slaves
  remote_user: ansible
  become_user: root
  become: true
  become_method: sudo 
  connection: ssh
  gather_facts: false

  vars_files:
    - ../local_variable_files/local-vars.yml

########################################################################################
# start tasks
########################################################################################

  tasks:
  # - name: create {{ jboss_wildfly_compressed_dir }}, if it does not exist
  #   file:
  #     path: "{{ jboss_wildfly_compressed_dir }}"
  #     state: directory
  #     mode: 0755
  #     recurse: yes
    
  - name: Test if "{{ jboss_wildfly_install }}/standalone/deployments/{{ jboss_wildfly_app_name }}" already exists.
    stat:
      path: "{{ jboss_wildfly_install }}/standalone/deployments/{{ jboss_wildfly_app_name }}"
    register: hd_file

  # - name: Download {{ jboss_wildfly_app_name }} into {{ jboss_wildfly_compressed_dir }}, when {{ jboss_wildfly_app_name }} does not exist.
  #   get_url:
  #     url:  "{{ jboss_wildfly_app_url }}"
  #     dest: "{{ jboss_wildfly_compressed_dir }}/{{ jboss_wildfly_app_name }}"
  #   when:  hd_file.stat.exists == False

  - name: Copy {{ jboss_wildfly_app_name }} to {{ jboss_wildfly_install }}/standalone/deployments/, when it does not exist
    copy:
      src: "{{ jboss_wildfly_compressed_dir }}/{{ jboss_wildfly_app_name }}"
      dest: "{{ jboss_wildfly_install }}/standalone/deployments/{{ jboss_wildfly_app_name }}"
      owner: "{{ jboss_wildfly_user_name }}"
      group: "{{ jboss_wildfly_user_group }}"
      mode: 0644
    when: hd_file.stat.exists == False

  # delete temp files that tend to accumulate in the user ansible's home dir
  # place at the bottom of all playbooks
  - include: ../../local_includes/delete-ansible-tmp-files.yml
